### ISSUE TITLE
CM13 & TWRP 3.0.0.0 on jfltexx not accepting right 5x5 decryption Pattern

### ISSUE THREAD

**Issue by EXTREMEGABEL** [TeamWin/Team-Win-Recovery-Project#588]

**Comment by player-03** [comment]
Experiencing the same on shamu.

To reproduce:
1. Create a new encryption pattern by going to settings -> lock screen -> screen lock -> pattern. When prompted, make sure "require pattern to start device" is checked, then create a 5x5 pattern.
2. Reboot into recovery mode.
3. On the "decrypt data" screen, tap the 5x5 button and enter the pattern you chose.

Result: TWRP will respond with "Pattern failed, please try again!"
Expected result: TWRP will successfully decrypt the partition.

Other notes:
- CyanogenMod can decrypt the partition using the same 5x5 pattern (as expected).
- Following those steps for a 3x3 pattern allows TWRP to decrypt the partition.

**Comment by Pietia10** [comment]
Cm 13 nightly oneplus one(bacon) and TWRP 3.0.0.1 same bug even with 3x3 pattern.

**Comment by EchoDev** [comment]
Decryption also fails with PIN on CM13 nightly and TWRP 3.0.0.x

**Comment by radumas** [comment]
Ditto hammerhead and 6x6 pattern

**Comment by Stokel** [comment]
Same with password and also after changing to 5x5 and 3x3

**Comment by nickalleyne** [comment]
This seems to be happening for me also when using a pin code, and on stable 12.1 CM with TWRP 3.0.0.x

**Comment by chuegel** [comment]
Failes also with Exodus 6. TWRP wont accept correct PIN. Had to format data to remove encryption

**Comment by zhimsel** [comment]
Same issue happening with me on Bacon with CM13 nightlies and TWRP (2.6.8.0-3.0.0-1). I tried with password, pin, and pattern.

**Comment by briancross** [comment]
Same issue with oneplus2 on CM13 and TWRP 3.0.0-2 (2.8.7.2 also). No option to enter my PIN as a "PIN", and entering it as text with the QWERTY keyboard fails as well.

Can flash /system just fine, but have to sideload, USB-OTG, or flash small zips from /cache as I cannot access /data to get to /data/media.

**Comment by ihor-sviziev** [comment]
I have same issue as @briancross on 3.0.0-2 for OnePlus 2 + Unofficial CM 13 by Grarak. Please fix this issue.

**Comment by briancross** [comment]
It's a ROM issue, not recovery and should be fixed in his latest build or
any build using his sources. I haven't had a chance to treat myself though.

**Comment by Pietia10** [comment]
No , in rom encryption works fine in twrp not so its not rom issue.
24.03.2016 22:30 "briancross" notifications@github.com napisał(a):

> It's a ROM issue, not recovery and should be fixed in his latest build or
> any build using his sources. I haven't had a chance to treat myself though.

**Comment by briancross** [comment]
No, it has to do with where the ROM stores the encryption key. Previously it was not storing it where TWRP was looking. If you've encrypted, you may need to wipe and reencrypt.

Read here: https://github.com/TeamWin/android_device_oneplus_oneplus2/issues/1

**Comment by Pietia10** [comment]
Is this fix applied already into bacon (oneplus one) ? Cause I dont think
so .
24.03.2016 23:12 "briancross" notifications@github.com napisał(a):

**Comment by Pietia10** [comment]
I have found it , 
https://github.com/CyanogenMod/android_device_oneplus_bacon/blob/49317589d024e5da00a2f9be72bccfaad71fde79/bacon.mk

there is already 
PRODUCT_PACKAGES += \
    keystore.msm8974

and it still doesn't works.

**Comment by h-2** [comment]
Any news? Is this was always so complicated, I had had hoped it had gotten better :cry: 
Isn't it all platform independent now with Android M and TWRP3?

Anything I can do to help track this down? [OPO / CM13 / TWRP-3.0.2]

Thank you very much.

**Comment by radumas** [comment]
Seems to be fixed in 3.0.2

**Comment by aredington** [comment]
I'm still seeing this on a OnePlus One with COS 13.0-ZNH0EAS2JK, TWRP-3.0.2-0

**Comment by nickalleyne** [comment]
For everyone who has this issue, can you please check the following.

When you are using any apps that use "Accessibility options" in android, android sets the encryption key back to the default password.  Examples of apps that can use this are LastPass or Tasker.

I have not yet confirmed, as I just wiped my phone and have kept all accessibility options off so far, but In this case, the password should be: default_password

See the following bug at google's side: https://code.google.com/p/android/issues/detail?id=79309

**Comment by Stokel** [comment]
Fresh CM13 nightly install and immediately encrypting without installing any apps still leads to this problem on Galaxy S4 (i9506). So I don't think that the accessibility options are the cause.

**Comment by zhimsel** [comment]
For those on bacon: https://github.com/TeamWin/Team-Win-Recovery-Project/issues/596#issuecomment-215315628

^ works for me.

**Comment by Frioo** [comment]
Can't decrypt data, 3x3 pattern lock.
Decryption fails even though I'm certain my PIN is correct.
No ROM installed (wiped, then updated TWRP from 3.0.2-1 to 3.0.3-1 because of another bug).
What should I do?

**Comment by Hello71** [comment]
if you upgraded from old version of CM, try using old "hex grid" method from #323 via command line.

**Comment by lindhe** [comment]
I have no lock pattern, only pin. Decryption fails with correct pin. Do you think I am experience this same bug, even though I never set a lock pattern?

**Comment by player-03** [comment]
I don't think so. This bug is now fixed.

**Comment by DrDoctor13** [comment]
I'm experiencing this with a pattern on TWRP 3.2.1 with Sultan's Oneplus3 Nougat ROM.

**Comment by ghost** [comment]
Same in 3.2.3-0

**Comment by guoyunhe** [comment]
Nexus 5, unofficial LineageOS 15.1. Encrypted with PIN. Cannot decrypt.

**Comment by landry314** [comment]
The problem I have is my phone was stuck in boot loop and so i had to install a modified version of TWRP "TWRP3_1_1_5X.img" after a new boot partition but this version will not decrypt my drive because it wont take my password so I am still not able to get my files...

**Comment by tengwar** [comment]
For people with PIN encryption stumbling onto this bug: upgrading TWRP helped. I had 3.2.3-0, upgraded to 3.3.1-0 and decryption works now. I'm not sure whether it's the new TWRP version or the reflash that helped.

**Comment by osie01hack** [comment]
Hello I have the same problem with data and all file encryption pin ---- on twrp . all you have to do is turns off your password on your phone and tried is work 100% .....this problem is a mess but resolved my xiaomi mi mix2 is rooted .🙃👍

**Comment by The-SamminAter** [comment]
Vsmart Joy 1, (ported) TWRP 3.18.140

Same problem, when I enter the right password, no matter what format, with or without boot protection, it fails.
