### ISSUE TITLE
TWRP Restore not finishing/ Stuck on 100%

### ISSUE THREAD

**Issue by CallumJC** [TeamWin/Team-Win-Recovery-Project#819]
I am trying to restore my Oneplus 3 back to the backup I made before I had rooted. 
The root worked but my efs was empty. 
So, I tried to restore my backup, but it is stuck on 100% and not telling me I can reboot or anything

What do i do?

![screenshot_2017-01-08-04-58-32 1](https://cloud.githubusercontent.com/assets/24987370/21749194/95dca854-d591-11e6-806d-0f130a3c8b64.png)

**Comment by CallumJC** [comment]
Nevermind, i managed to get out of it

**Comment by danieelso** [comment]
Hey please CallumJC, where's the solution? This bug is really annoying... help!

**Comment by CallumJC** [comment]
I just held down the power button until my phone turned off. I then took me to the 'please lock phone boot loader' screen, which I could boot into anything after, and it then turned it back on. For me it restored, so I hope it does for you

**Comment by jcadduono** [comment]
try 3.0.3 I just released for OP3 (you will likely need to make new backups for EFS/Modem, they probably will not be compatible)

**Comment by CallumJC** [comment]
Thanks

**Comment by TimothyShimmin** [comment]
I'm having a similar problem on Nexus 5X, Nougat, TWRP 3.1.1-0. Hangs on 99%

**Comment by zakwilson** [comment]
I'm having the same issue. TWRP 3.1.1-0 on my Nexus 5, but it was doing the same with an older version. It seems inconsistent about exactly where it stops, but around 99% of the data. The file count doesn't seem to line up right and it sometimes exceeds 100%, but still hangs rather than completing.

It used to complete successfully, and stopped doing so without having updated TWRP.
